In [ ]:
some changes

In [ ]:
Hello

In [2]:
import pandas as pd
import scipy
import numpy as np


In [ ]:
hello

In [3]:
df = pd.read_csv('gamelog2020.csv')  

In [4]:
df

Date Visiting Team  Visiting team game num   Home  \
0    "20200723"         "SFN"                       1  "LAN"   
1    "20200723"         "NYA"                       1  "WAS"   
2    "20200724"         "MIL"                       1  "CHN"   
3    "20200724"         "DET"                       1  "CIN"   
4    "20200724"         "SFN"                       2  "LAN"   
..          ...           ...                     ...    ...   
893  "20200927"         "MIA"                      60  "NYA"   
894  "20200927"         "SEA"                      60  "OAK"   
895  "20200927"         "PHI"                      60  "TBA"   
896  "20200927"         "HOU"                      60  "TEX"   
897  "20200927"         "BAL"                      60  "TOR"   

     Home team game num  Visiting final score  Home final score  Num outs  \
0                     1                     1                 8        51   
1                     1                     4                 1        31   
2                     1                     0                 3        51   
3                     1                     1                 7        51   
4                     2                     1                 9        51   
..                  ...                   ...               ...       ...   
893                  60                     5                 0        54   
894                  60                     2                 6        51   
895                  60                     0                 5        51   
896                  60                     4                 8        51   
897                  60                     7                 5        54   

    Ballpark   Visit line    Home line  Unnamed: 11  
0    "LOS03"  "001000000"  "00010052x"          NaN  
1    "WAS11"     "201010"     "10000x"          NaN  
2    "CHI11"  "000000000"  "00200001x"          NaN  
3    "CIN09"  "000100000"  "20101120x"          NaN  
4    "LOS03"  "001000000"  "11011122x"          NaN  
..       ...          ...          ...          ...  
893  "NYC21"  "030010010"  "000000000"         35.0  
894  "OAK01"  "110000000"  "10001031x"         32.0  
895  "STP01"  "000000000"  "01200200x"         32.0  
896  "ARL02"  "101100010"  "01051010x"         35.0  
897  "BUF05"  "001330000"  "013000010"         35.0  

[898 rows x 12 columns]

In [10]:
away = df["Visit line"]
home = df["Home line"]

In [23]:
away = df["Visiting final score"].to_numpy()
home = df["Home final score"].to_numpy()
awayandhome = away+home
num_outs = df["Num outs"].to_numpy()

In [24]:
np.corrcoef(awayandhome, num_outs)

array([[1.        , 0.10023742],
       [0.10023742, 1.        ]])

In [26]:
from sklearn.linear_model import LinearRegression

In [39]:
X = np.array([away, home])
y = num_outs

In [37]:
X.shape, y.shape

((2, 898), (898,))

array([[1, 8],
       [4, 1],
       [0, 3],
       ...,
       [0, 5],
       [4, 8],
       [7, 5]])

In [40]:
reg = LinearRegression().fit(X.T, y)

In [41]:
reg.coef_

array([ 0.3226959 , -0.12175951])

In [43]:
reg.score(X.T, y)

0.051600416212623346